### ISSUE TITLE
There is a way to use this as shaders? (in emulators like dolphin)

### ISSUE THREAD

**Issue by charmandercha** [yui0/waifu2x-glsl#2]
Or is this technology too slow to do something like that?

**Comment by yui0** [comment]
I think that your idea is very good.
But I'm sorry.
This technology does not fit the idea.
There are two reasons. First of all, this program is not designed for the idea. If you want to use it, you need to modify it very much. Second, this algorithm is too slow to use it. Maybe this problem happens to other similar programs.
